/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as CertificatesIdRouteImport } from './routes/certificates.$id'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated/badges'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedInterviewIndexRouteImport } from './routes/_authenticated/interview.index'
import { Route as AuthenticatedAssessmentsIndexRouteImport } from './routes/_authenticated/assessments.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSupportIdRouteImport } from './routes/_authenticated/support.$id'
import { Route as AuthenticatedSkillsIdRouteImport } from './routes/_authenticated/skills.$id'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedInterviewSessionIdRouteImport } from './routes/_authenticated/interview.$sessionId'
import { Route as AuthenticatedAssessmentsHistoryRouteImport } from './routes/_authenticated/assessments.history'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSkillsRouteImport } from './routes/_authenticated/admin.skills'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminFraudRouteImport } from './routes/_authenticated/admin.fraud'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as AuthenticatedAdminBadgesRouteImport } from './routes/_authenticated/admin.badges'
import { Route as AuthenticatedAdminAssessmentsRouteImport } from './routes/_authenticated/admin.assessments'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAssessmentsAttemptIdRouteImport } from './routes/_authenticated/assessments.attempt.$id'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIdRoute = CertificatesIdRouteImport.update({
  id: '/certificates/$id',
  path: '/certificates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewIndexRoute =
  AuthenticatedInterviewIndexRouteImport.update({
    id: '/interview/',
    path: '/interview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsIndexRoute =
  AuthenticatedAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportIdRoute = AuthenticatedSupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSupportRoute,
} as any)
const AuthenticatedSkillsIdRoute = AuthenticatedSkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSkillsRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewSessionIdRoute =
  AuthenticatedInterviewSessionIdRouteImport.update({
    id: '/interview/$sessionId',
    path: '/interview/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsHistoryRoute =
  AuthenticatedAssessmentsHistoryRouteImport.update({
    id: '/assessments/history',
    path: '/assessments/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSkillsRoute =
  AuthenticatedAdminSkillsRouteImport.update({
    id: '/admin/skills',
    path: '/admin/skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/admin/questions',
    path: '/admin/questions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFraudRoute = AuthenticatedAdminFraudRouteImport.update({
  id: '/admin/fraud',
  path: '/admin/fraud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/admin/certificates',
    path: '/admin/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBadgesRoute =
  AuthenticatedAdminBadgesRouteImport.update({
    id: '/admin/badges',
    path: '/admin/badges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAssessmentsRoute =
  AuthenticatedAdminAssessmentsRouteImport.update({
    id: '/admin/assessments',
    path: '/admin/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsAttemptIdRoute =
  AuthenticatedAssessmentsAttemptIdRouteImport.update({
    id: '/assessments/attempt/$id',
    path: '/assessments/attempt/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/skills': typeof AuthenticatedSkillsRouteWithChildren
  '/support': typeof AuthenticatedSupportRouteWithChildren
  '/certificates/$id': typeof CertificatesIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/assessments/history': typeof AuthenticatedAssessmentsHistoryRoute
  '/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/skills/$id': typeof AuthenticatedSkillsIdRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/interview/': typeof AuthenticatedInterviewIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/assessments/attempt/$id': typeof AuthenticatedAssessmentsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/skills': typeof AuthenticatedSkillsRouteWithChildren
  '/support': typeof AuthenticatedSupportRouteWithChildren
  '/certificates/$id': typeof CertificatesIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/assessments/history': typeof AuthenticatedAssessmentsHistoryRoute
  '/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/skills/$id': typeof AuthenticatedSkillsIdRoute
  '/support/$id': typeof AuthenticatedSupportIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/interview': typeof AuthenticatedInterviewIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/assessments/attempt/$id': typeof AuthenticatedAssessmentsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRouteWithChildren
  '/_authenticated/support': typeof AuthenticatedSupportRouteWithChildren
  '/certificates/$id': typeof CertificatesIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/_authenticated/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/assessments/history': typeof AuthenticatedAssessmentsHistoryRoute
  '/_authenticated/interview/$sessionId': typeof AuthenticatedInterviewSessionIdRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/skills/$id': typeof AuthenticatedSkillsIdRoute
  '/_authenticated/support/$id': typeof AuthenticatedSupportIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/_authenticated/interview/': typeof AuthenticatedInterviewIndexRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/assessments/attempt/$id': typeof AuthenticatedAssessmentsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/analytics'
    | '/badges'
    | '/certificates'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/skills'
    | '/support'
    | '/certificates/$id'
    | '/verify/$id'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/badges'
    | '/admin/certificates'
    | '/admin/fraud'
    | '/admin/notifications'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/support'
    | '/admin/users'
    | '/assessments/history'
    | '/interview/$sessionId'
    | '/settings/notifications'
    | '/skills/$id'
    | '/support/$id'
    | '/admin/'
    | '/assessments/'
    | '/interview/'
    | '/admin/users/$id'
    | '/assessments/attempt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/analytics'
    | '/badges'
    | '/certificates'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/skills'
    | '/support'
    | '/certificates/$id'
    | '/verify/$id'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/badges'
    | '/admin/certificates'
    | '/admin/fraud'
    | '/admin/notifications'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/support'
    | '/admin/users'
    | '/assessments/history'
    | '/interview/$sessionId'
    | '/settings/notifications'
    | '/skills/$id'
    | '/support/$id'
    | '/admin'
    | '/assessments'
    | '/interview'
    | '/admin/users/$id'
    | '/assessments/attempt/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/badges'
    | '/_authenticated/certificates'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/skills'
    | '/_authenticated/support'
    | '/certificates/$id'
    | '/verify/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/assessments'
    | '/_authenticated/admin/badges'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/fraud'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/skills'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/assessments/history'
    | '/_authenticated/interview/$sessionId'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/skills/$id'
    | '/_authenticated/support/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/assessments/'
    | '/_authenticated/interview/'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/assessments/attempt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CertificatesIdRoute: typeof CertificatesIdRoute
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$id': {
      id: '/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof CertificatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/': {
      id: '/_authenticated/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof AuthenticatedInterviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/': {
      id: '/_authenticated/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthenticatedAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/$id': {
      id: '/_authenticated/support/$id'
      path: '/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof AuthenticatedSupportIdRouteImport
      parentRoute: typeof AuthenticatedSupportRoute
    }
    '/_authenticated/skills/$id': {
      id: '/_authenticated/skills/$id'
      path: '/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof AuthenticatedSkillsIdRouteImport
      parentRoute: typeof AuthenticatedSkillsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$sessionId': {
      id: '/_authenticated/interview/$sessionId'
      path: '/interview/$sessionId'
      fullPath: '/interview/$sessionId'
      preLoaderRoute: typeof AuthenticatedInterviewSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/history': {
      id: '/_authenticated/assessments/history'
      path: '/assessments/history'
      fullPath: '/assessments/history'
      preLoaderRoute: typeof AuthenticatedAssessmentsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/skills': {
      id: '/_authenticated/admin/skills'
      path: '/admin/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthenticatedAdminSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fraud': {
      id: '/_authenticated/admin/fraud'
      path: '/admin/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AuthenticatedAdminFraudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/badges': {
      id: '/_authenticated/admin/badges'
      path: '/admin/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AuthenticatedAdminBadgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/assessments': {
      id: '/_authenticated/admin/assessments'
      path: '/admin/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AuthenticatedAdminAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/attempt/$id': {
      id: '/_authenticated/assessments/attempt/$id'
      path: '/assessments/attempt/$id'
      fullPath: '/assessments/attempt/$id'
      preLoaderRoute: typeof AuthenticatedAssessmentsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
  }
}

interface AuthenticatedSkillsRouteChildren {
  AuthenticatedSkillsIdRoute: typeof AuthenticatedSkillsIdRoute
}

const AuthenticatedSkillsRouteChildren: AuthenticatedSkillsRouteChildren = {
  AuthenticatedSkillsIdRoute: AuthenticatedSkillsIdRoute,
}

const AuthenticatedSkillsRouteWithChildren =
  AuthenticatedSkillsRoute._addFileChildren(AuthenticatedSkillsRouteChildren)

interface AuthenticatedSupportRouteChildren {
  AuthenticatedSupportIdRoute: typeof AuthenticatedSupportIdRoute
}

const AuthenticatedSupportRouteChildren: AuthenticatedSupportRouteChildren = {
  AuthenticatedSupportIdRoute: AuthenticatedSupportIdRoute,
}

const AuthenticatedSupportRouteWithChildren =
  AuthenticatedSupportRoute._addFileChildren(AuthenticatedSupportRouteChildren)

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRouteWithChildren
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRouteWithChildren
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAssessmentsRoute: typeof AuthenticatedAdminAssessmentsRoute
  AuthenticatedAdminBadgesRoute: typeof AuthenticatedAdminBadgesRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminFraudRoute: typeof AuthenticatedAdminFraudRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSkillsRoute: typeof AuthenticatedAdminSkillsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAssessmentsHistoryRoute: typeof AuthenticatedAssessmentsHistoryRoute
  AuthenticatedInterviewSessionIdRoute: typeof AuthenticatedInterviewSessionIdRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAssessmentsIndexRoute: typeof AuthenticatedAssessmentsIndexRoute
  AuthenticatedInterviewIndexRoute: typeof AuthenticatedInterviewIndexRoute
  AuthenticatedAssessmentsAttemptIdRoute: typeof AuthenticatedAssessmentsAttemptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRouteWithChildren,
  AuthenticatedSupportRoute: AuthenticatedSupportRouteWithChildren,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAssessmentsRoute: AuthenticatedAdminAssessmentsRoute,
  AuthenticatedAdminBadgesRoute: AuthenticatedAdminBadgesRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminFraudRoute: AuthenticatedAdminFraudRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSkillsRoute: AuthenticatedAdminSkillsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAssessmentsHistoryRoute: AuthenticatedAssessmentsHistoryRoute,
  AuthenticatedInterviewSessionIdRoute: AuthenticatedInterviewSessionIdRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAssessmentsIndexRoute: AuthenticatedAssessmentsIndexRoute,
  AuthenticatedInterviewIndexRoute: AuthenticatedInterviewIndexRoute,
  AuthenticatedAssessmentsAttemptIdRoute:
    AuthenticatedAssessmentsAttemptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CertificatesIdRoute: CertificatesIdRoute,
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
